# Generated by Django 2.2 on 2020-12-31 00:56

import common.uploads
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='PumpCompareReport',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Name', max_length=255)),
                ('date_saved', models.DateTimeField(auto_now_add=True, help_text='Date Saved')),
                ('started_from', models.DateTimeField(help_text='Started From', null=True)),
                ('description', models.TextField(blank=True, help_text='Description', null=True)),
                ('upload', models.FileField(upload_to=common.uploads.pump_compare_upload)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
