# Generated by Django 2.2 on 2019-07-29 14:51

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('geo', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='WaterUtility',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Water System Name / Utility Name', max_length=255)),
                ('water_system_id', models.CharField(max_length=20, unique=True)),
                ('population', models.PositiveIntegerField(default=0, help_text='Population Served')),
                ('num_meters', models.PositiveIntegerField(default=0, help_text='Number of Meters')),
                ('primary_water_source_type', models.PositiveIntegerField(choices=[(1, 'Ground water'), (2, 'Ground water purchased'), (3, 'Groundwater under influence of surface water'), (4, 'Purchased ground water under influence of surface water source'), (5, 'Surface water'), (6, 'Surface water purchased')], help_text='Primary Water Source Type')),
                ('water_system_type', models.PositiveIntegerField(choices=[(1, 'Community Water Systems'), (2, 'Non-Transient Non-Community Water Systems')], help_text='Water System Type')),
                ('is_pws_activity_active', models.BooleanField(help_text='Is PWS Activity enabled?')),
                ('location', models.OneToOneField(help_text='Location / Address', on_delete=django.db.models.deletion.CASCADE, to='geo.Address')),
            ],
            options={
                'verbose_name_plural': 'Water utilities',
            },
        ),
        migrations.CreateModel(
            name='AssetFinance',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('asset_name', models.CharField(help_text='Asset Name', max_length=255)),
                ('projected_unscheduled_amount', models.FloatField(help_text='Project Unscheduled', validators=[django.core.validators.MinValueValidator(0.0)])),
                ('projected_scheduled_amount', models.FloatField(help_text='Project Scheduled', validators=[django.core.validators.MinValueValidator(0.0)])),
                ('allocated_budget', models.FloatField(help_text='Allocated Budget', validators=[django.core.validators.MinValueValidator(0.0)])),
                ('average_service_life', models.PositiveIntegerField(help_text='Average Service Life in Years')),
                ('water_utility', models.ForeignKey(help_text='Water Utility', on_delete=django.db.models.deletion.CASCADE, to='utility.WaterUtility')),
            ],
        ),
    ]
