# Generated by Django 2.2 on 2019-07-30 17:20

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('utility', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='WaterQuality',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateTimeField(help_text='Date and time the quality data has been recorded')),
                ('barium', models.FloatField(blank=True, null=True)),
                ('fluoride', models.FloatField(blank=True, null=True)),
                ('nitrate', models.FloatField(blank=True, null=True)),
                ('sodium', models.FloatField(blank=True, null=True)),
                ('haa5', models.FloatField(blank=True, null=True)),
                ('tthm', models.FloatField(blank=True, null=True)),
                ('copper', models.FloatField(blank=True, null=True)),
                ('lead', models.FloatField(blank=True, null=True)),
                ('orp', models.FloatField(blank=True, null=True)),
                ('chlorine', models.FloatField(blank=True, null=True)),
                ('water_utility', models.ForeignKey(help_text='Water Utility', on_delete=django.db.models.deletion.CASCADE, to='utility.WaterUtility')),
            ],
            options={
                'verbose_name_plural': 'Water qualities',
            },
        ),
    ]
