# Generated by Django 2.2 on 2019-08-08 17:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('utility', '0003_waterutility_url'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='waterquality',
            unique_together={('date', 'water_utility')},
        ),
    ]
