# Generated by Django 2.2 on 2019-08-08 19:14

import common.utils
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('utility', '0004_auto_20190808_1246'),
    ]

    operations = [
        migrations.AddField(
            model_name='assetfinance',
            name='year',
            field=models.PositiveIntegerField(default=common.utils.get_current_year, help_text='Fiscal Year'),
        ),
        migrations.AlterUniqueTogether(
            name='assetfinance',
            unique_together={('water_utility', 'year', 'asset_name')},
        ),
    ]
