# Generated by Django 2.2 on 2019-08-17 14:36

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('utility', '0005_auto_20190808_1414'),
    ]

    operations = [
        migrations.CreateModel(
            name='Sensor',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('longitude', models.FloatField()),
                ('latitude', models.FloatField()),
                ('device_id', models.CharField(help_text='Real Device ID', max_length=255, unique=True)),
                ('water_utility', models.ForeignKey(help_text='Water Utility this sensor belongs to', on_delete=django.db.models.deletion.CASCADE, to='utility.WaterUtility')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='SensorDataRecord',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('recorded_at', models.DateTimeField(help_text='Date and time the sensor value has been recorded at.')),
                ('orp', models.FloatField(blank=True, help_text='Oxidation Reduction Potential value in mV obtained from the sensor.', null=True)),
                ('sensor', models.ForeignKey(help_text='Sensor', on_delete=django.db.models.deletion.CASCADE, to='utility.Sensor', related_name='records')),
            ],
        ),
        migrations.CreateModel(
            name='Alert',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('alert_type', models.IntegerField(choices=[(1, 'Critical'), (2, 'Info'), (3, 'Warning')], help_text='Alert type based on severity or information')),
                ('reported_at', models.DateTimeField(help_text='Date and time the alert has been reported')),
                ('message', models.TextField(blank=True, null=True)),
                ('status', models.IntegerField(choices=[(1, 'In process'), (2, 'Ongoing'), (3, 'Resolved')], help_text='Current status of the alert')),
                ('sensor_data_record', models.OneToOneField(help_text='Sensor', on_delete=django.db.models.deletion.CASCADE, to='utility.SensorDataRecord', related_name='alert')),
            ],
        ),
    ]
