# Generated by Django 2.2 on 2019-12-21 15:46

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('utility', '0009_auto_20191220_1706'),
    ]

    operations = [
        migrations.CreateModel(
            name='SiteVisitDetail',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cat', models.CharField(blank=True, max_length=40, null=True)),
                ('sev', models.CharField(blank=True, max_length=40, null=True)),
                ('desc_code', models.CharField(blank=True, max_length=40, null=True)),
                ('desc_text', models.CharField(blank=True, max_length=40, null=True)),
                ('freehand_desc', models.CharField(blank=True, max_length=40, null=True)),
                ('det_date', models.DateField(null=True)),
                ('res_date', models.DateField(null=True)),
                ('site_visit', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='utility.SiteVisit')),
            ],
        ),
        migrations.RenameModel(
            old_name='Violations',
            new_name='Violation',
        ),
        migrations.AlterField(
            model_name='contact',
            name='business_phone1',
            field=models.CharField(blank=True, help_text='First Business Phone Number', max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='contact',
            name='business_phone2',
            field=models.CharField(blank=True, help_text='Second Business Phone Number', max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='contact',
            name='email1',
            field=models.EmailField(blank=True, help_text='First Email', max_length=254, null=True),
        ),
        migrations.AlterField(
            model_name='contact',
            name='email2',
            field=models.EmailField(blank=True, help_text='Second Email', max_length=254, null=True),
        ),
        migrations.AlterField(
            model_name='contact',
            name='fax',
            field=models.CharField(blank=True, help_text='Facsimile', max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='contact',
            name='middle_name',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='contact',
            name='mobile_phone',
            field=models.CharField(blank=True, help_text='Mobile Phone Number', max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='nontcrsample',
            name='method',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='nontcrsample',
            name='result',
            field=models.CharField(blank=True, help_text='Measure for PBCU sample, Result for other sample', max_length=10, null=True),
        ),
        migrations.AlterField(
            model_name='nontcrsample',
            name='unit',
            field=models.CharField(blank=True, choices=[('MG/L', 'MG/L')], max_length=10, null=True),
        ),
        migrations.AlterField(
            model_name='nontcrsampleschedule',
            name='end_date',
            field=models.DateField(null=True),
        ),
        migrations.AlterField(
            model_name='nontcrsampleschedule',
            name='seasonal',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='sale',
            name='availability',
            field=models.CharField(blank=True, choices=[('', 'Blank'), ('S', 'Seasonal'), ('E', 'Emergency'), ('I', 'Interim'), ('P', 'Permanent'), ('O', 'Other')], max_length=1, null=True),
        ),
        migrations.AlterField(
            model_name='tcrsampleresult',
            name='method',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
        migrations.AlterField(
            model_name='tcrsampleschedule',
            name='end_date',
            field=models.DateField(null=True),
        ),
        migrations.AlterField(
            model_name='waterutility',
            name='principal_city_served',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='waterutility',
            name='principal_county_served',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.DeleteModel(
            name='SIteVisitDetails',
        ),
    ]
