# Generated by Django 2.2 on 2019-12-23 14:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('utility', '0010_auto_20191221_0946'),
    ]

    operations = [
        migrations.AlterField(
            model_name='waterutility',
            name='is_pws_activity_active',
            field=models.BooleanField(default=False, help_text='Is PWS Activity enabled?'),
        ),
    ]
