# Generated by Django 2.2 on 2019-12-23 19:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('utility', '0011_auto_20191223_0802'),
    ]

    operations = [
        migrations.AddField(
            model_name='annualoperatingperiod',
            name='population',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
