# Generated by Django 2.2 on 2019-12-23 21:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('utility', '0012_annualoperatingperiod_population'),
    ]

    operations = [
        migrations.RenameField(
            model_name='facilityflow',
            old_name='supplyer',
            new_name='supplier',
        ),
    ]
