# Generated by Django 2.2 on 2019-12-23 22:48

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('utility', '0013_auto_20191223_1512'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tcrsampleschedule',
            name='original_sample',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='utility.TcrSample'),
        ),
    ]
