# Generated by Django 2.2 on 2019-12-23 23:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('utility', '0015_auto_20191223_1659'),
    ]

    operations = [
        migrations.AlterField(
            model_name='nontcrsampleschedule',
            name='init_mp_begin_date',
            field=models.DateField(blank=True, help_text='Init MP Begin Date', null=True),
        ),
    ]
