# Generated by Django 2.2 on 2019-12-24 01:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('utility', '0016_auto_20191223_1758'),
    ]

    operations = [
        migrations.AlterField(
            model_name='violation',
            name='fiscal_year',
            field=models.PositiveIntegerField(help_text='Federal Fiscal Year for Group Violation', null=True),
        ),
        migrations.AlterField(
            model_name='violation',
            name='violation_id',
            field=models.CharField(blank=True, help_text='Vialation No. for Individual Violation', max_length=10, null=True),
        ),
    ]
