# Generated by Django 2.2 on 2019-12-24 02:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('utility', '0018_tcrsample_result_summary'),
    ]

    operations = [
        migrations.AddField(
            model_name='tcrsample',
            name='rp_loc',
            field=models.CharField(blank=True, max_length=40, null=True),
        ),
    ]
