# Generated by Django 2.2 on 2019-12-24 03:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('utility', '0019_tcrsample_rp_loc'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tcrsample',
            name='sample_id',
            field=models.CharField(help_text='Sample No.', max_length=20),
        ),
    ]
