# Generated by Django 2.2 on 2019-12-24 03:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('utility', '0021_auto_20191223_2107'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tcrsampleresult',
            name='mp_date1',
            field=models.DateField(null=True),
        ),
        migrations.AlterField(
            model_name='tcrsampleresult',
            name='mp_date2',
            field=models.DateField(null=True),
        ),
    ]
