# Generated by Django 2.2 on 2019-12-24 04:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('utility', '0022_auto_20191223_2108'),
    ]

    operations = [
        migrations.AlterField(
            model_name='nontcrsample',
            name='pbcu_type',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
        migrations.AlterField(
            model_name='nontcrsample',
            name='site',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
    ]
