# Generated by Django 2.2 on 2019-12-24 04:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('utility', '0024_auto_20191223_2217'),
    ]

    operations = [
        migrations.AlterField(
            model_name='nontcrsample',
            name='sample_type',
            field=models.CharField(choices=[('PBCU', 'PBCU'), ('primary/secondary', 'Primary / Secondary'), ('SOC', 'SOC'), ('RVOC', 'RVOC')], max_length=50),
        ),
    ]
