# Generated by Django 2.2 on 2019-12-24 05:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('utility', '0026_auto_20191223_2220'),
    ]

    operations = [
        migrations.AlterField(
            model_name='nontcrsample',
            name='date2',
            field=models.DateField(blank=True, help_text='MP End Date for PBCU sample, leave as blank for other sample', null=True),
        ),
    ]
