# Generated by Django 2.2 on 2019-12-24 14:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('utility', '0027_auto_20191223_2337'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sitevisitdetail',
            name='desc_code',
            field=models.CharField(blank=True, max_length=250, null=True),
        ),
        migrations.AlterField(
            model_name='sitevisitdetail',
            name='desc_text',
            field=models.CharField(blank=True, max_length=250, null=True),
        ),
        migrations.AlterField(
            model_name='sitevisitdetail',
            name='freehand_desc',
            field=models.CharField(blank=True, max_length=250, null=True),
        ),
        migrations.AlterField(
            model_name='tcrsampleresult',
            name='method',
            field=models.CharField(blank=True, max_length=40, null=True),
        ),
    ]
