# Generated by Django 2.2 on 2019-12-24 14:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('utility', '0028_auto_20191224_0809'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tcrsample',
            name='tcr_type',
            field=models.CharField(choices=[('RT', 'Routine'), ('RP', 'Repeat')], help_text='Type / RP Loc', max_length=10),
        ),
    ]
