# Generated by Django 2.2 on 2019-12-24 14:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('utility', '0029_auto_20191224_0823'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tcrsample',
            name='result_summary',
            field=models.CharField(blank=True, help_text='Ex: 11999 FM 321 LOT #1, G0660002G', max_length=250, null=True),
        ),
    ]
