# Generated by Django 2.2 on 2019-12-24 14:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('utility', '0030_auto_20191224_0832'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sitevisitdetail',
            name='freehand_desc',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
    ]
