# Generated by Django 2.2 on 2020-01-09 05:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('utility', '0031_auto_20191224_0839'),
    ]

    operations = [
        migrations.AlterField(
            model_name='waterutility',
            name='water_system_type',
            field=models.CharField(choices=[('C', 'Community Water System'), ('NC', 'Noncommunity Water System'), ('TNC', 'Transient, Noncommunity Water System'), ('NTNC', 'Nontransient, Noncommunity Water System')], max_length=4),
        ),
    ]
