# Generated by Django 2.2 on 2020-01-20 12:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('utility', '0032_auto_20200108_2305'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='sensordatarecord',
            name='orp',
        ),
        migrations.AddField(
            model_name='sensordatarecord',
            name='value',
            field=models.FloatField(blank=True, help_text='Value obtained from the sensor.', null=True),
        ),
        migrations.AddField(
            model_name='sensordatarecord',
            name='value_type',
            field=models.CharField(choices=[('barium', 'Barium'), ('fluoride', 'Fluoride'), ('nitrate', 'Nitrate'), ('sodium', 'Sodium'), ('haa5', 'Haa5'), ('tthm', 'TTHM'), ('copper', 'Copper'), ('Lead', 'Lead'), ('orp', 'Oxidation Reduction Potential'), ('chlorine', 'Chlorine')], default='orp', max_length=20),
        ),
    ]
