# Generated by Django 2.2 on 2020-01-20 14:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('utility', '0033_auto_20200120_0645'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sensordatarecord',
            name='value_type',
            field=models.CharField(choices=[('barium', 'Barium'), ('fluoride', 'Fluoride'), ('sodium', 'Nitrate'), ('sodium', 'Sodium'), ('haa5', 'Haa5'), ('tthm', 'TTHM'), ('copper', 'Copper'), ('lead', 'Lead'), ('orp', 'Oxidation Reduction Potential'), ('chlorine', 'Chlorine')], default='orp', max_length=20),
        ),
    ]
