# Generated by Django 2.2 on 2020-01-23 15:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('utility', '0034_auto_20200120_0856'),
    ]

    operations = [
        migrations.AddField(
            model_name='sensordatarecord',
            name='unit',
            field=models.CharField(default='mg/l', max_length=10),
        ),
    ]
