# Generated by Django 2.2 on 2020-01-27 19:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('utility', '0035_sensordatarecord_unit'),
    ]

    operations = [
        migrations.AlterField(
            model_name='alert',
            name='alert_type',
            field=models.IntegerField(choices=[(0, 'Info'), (1, 'Warning'), (2, 'Serious'), (3, 'Critical')], help_text='Alert type based on severity or information'),
        ),
    ]
