# Generated by Django 2.2 on 2020-02-12 05:32

import common.uploads
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('utility', '0036_auto_20200127_1349'),
    ]

    operations = [
        migrations.CreateModel(
            name='MonthlyReport',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('name', models.CharField(blank=True, help_text='By default, file will be downloaded as a name of {Water utility name}-{year}-{month} form. Override if you want to customize it.', max_length=512, null=True)),
                ('upload', models.FileField(upload_to=common.uploads.monthly_report_upload)),
                ('water_utility', models.ForeignKey(help_text='Water Utility', on_delete=django.db.models.deletion.CASCADE, to='utility.WaterUtility')),
            ],
        ),
    ]
