# Generated by Django 2.2 on 2020-07-10 04:00

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('geo', '0002_auto_20190808_1057'),
        ('utility', '0040_rawwater_timestamp'),
    ]

    operations = [
        migrations.AddField(
            model_name='sensor',
            name='location',
            field=models.OneToOneField(help_text='Location / Address', null=True, on_delete=django.db.models.deletion.CASCADE, to='geo.Address'),
        ),
    ]
