# Generated by Django 2.2 on 2020-07-10 04:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('utility', '0041_sensor_location'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='sensor',
            name='latitude',
        ),
        migrations.RemoveField(
            model_name='sensor',
            name='longitude',
        ),
    ]
