# Generated by Django 2.2 on 2021-01-25 23:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('utility', '0042_auto_20200709_2315'),
    ]

    operations = [
        migrations.AddField(
            model_name='sensordatarecord',
            name='value_str',
            field=models.CharField(max_length=128, null=True),
        ),
        migrations.AlterField(
            model_name='sensordatarecord',
            name='unit',
            field=models.CharField(default='mg/l', max_length=10, null=True),
        ),
        migrations.AlterField(
            model_name='sensordatarecord',
            name='value_type',
            field=models.CharField(choices=[('barium', 'Barium'), ('fluoride', 'Fluoride'), ('sodium', 'Nitrate'), ('sodium', 'Sodium'), ('haa5', 'Haa5'), ('tthm', 'TTHM'), ('copper', 'Copper'), ('lead', 'Lead'), ('orp', 'Oxidation Reduction Potential'), ('chlorine', 'Chlorine'), ('ph', 'PH'), ('turbidity', 'Turbidity'), ('water temperature', 'Water Temperature'), ('ambient temperature', 'Ambient Temperature'), ('battery voltage', 'Battery Voltage'), ('gps', 'GPS')], default='orp', max_length=20),
        ),
    ]
