# Generated by Django 3.1 on 2021-03-19 22:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('utility', '0043_auto_20210125_1756'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sensordatarecord',
            name='value_str',
            field=models.CharField(blank=True, max_length=128, null=True),
        ),
    ]
