# Generated by Django 3.1 on 2021-06-22 19:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('utility', '0044_auto_20210319_1710'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sensordatarecord',
            name='value_type',
            field=models.CharField(choices=[('barium', 'Barium'), ('fluoride', 'Fluoride'), ('sodium', 'Nitrate'), ('sodium', 'Sodium'), ('haa5', 'Haa5'), ('tthm', 'TTHM'), ('copper', 'Copper'), ('lead', 'Lead'), ('orp', 'Oxidation Reduction Potential'), ('chlorine', 'Chlorine'), ('ph', 'PH'), ('turbidity', 'Turbidity'), ('conductivity', 'Conductivity'), ('water temperature', 'Water Temperature'), ('ambient temperature', 'Ambient Temperature'), ('battery voltage', 'Battery Voltage'), ('gps', 'GPS')], default='orp', max_length=20),
        ),
    ]
