# Generated by Django 2.2 on 2019-07-29 12:51

from django.db import migrations, models
import jsonfield.fields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Address',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('street_address_1', models.CharField(blank=True, help_text='Street address 1', max_length=255, null=True)),
                ('street_address_2', models.CharField(blank=True, default='', help_text='Street address 2', max_length=255, null=True)),
                ('city', models.CharField(max_length=128)),
                ('state', models.CharField(help_text='State / Province', max_length=128)),
                ('zip_code', models.CharField(help_text='ZIP5', max_length=32)),
                ('country', models.CharField(max_length=128)),
                ('longitude', models.IntegerField()),
                ('latitude', models.IntegerField()),
                ('geocode_json', jsonfield.fields.JSONField(blank=True, default=None, help_text='Raw JSON response from google geocode', null=True)),
            ],
        ),
    ]
