# Generated by Django 2.2 on 2020-02-18 03:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0004_auto_20200217_2104'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='subscribe_desc',
            field=models.CharField(help_text='User left text when he signed up', max_length=1024),
        ),
    ]
