# Generated by Django 2.2 on 2020-02-20 04:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0006_auto_20200218_1248'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='subscribe_desc',
            field=models.TextField(help_text='User left text when he signed up', max_length=1024),
        ),
    ]
