# Generated by Django 3.1 on 2021-06-22 21:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0010_auto_20210316_1934'),
    ]

    operations = [
        migrations.CreateModel(
            name='Memo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('memo', models.TextField(blank=True, help_text='Memo', max_length=4096)),
                ('email_domain', models.TextField(default='', help_text='Email domain', max_length=32)),
            ],
        ),
    ]
